### ISSUE TITLE
error with region turkey TR

### ISSUE THREAD

**Issue by saifeealii** [frostysecurethebag/NightMarket-Checker#4]
Hi, i forgot to change the region in infogg file and my accounts were turkish region but the script started generating info for those accounts and the info was wrong. The moment i realised that the info is wrong, i changed region from na to tr but its giving an error now with tr region:

```
Traceback (most recent call last):
  File "C:\Users\saife\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\saife\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\saife\AppData\Local\Programs\Python\Python39\lib\socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\saife\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\saife\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\saife\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\saife\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 358, in connect
    conn = self._new_conn()
  File "C:\Users\saife\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001BB892C5640>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\saife\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "C:\Users\saife\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\saife\AppData\Local\Programs\Python\Python39\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pd.tr.a.pvp.net', port=443): Max retries exceeded with url: /store/v2/storefront/4facd75b-7814-5821-b035-8402bee2aef9 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BB892C5640>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\scripts\checker\NightMarket Checker\nmchecker.py", line 121, in <module>
    main()
  File "E:\scripts\checker\NightMarket Checker\nmchecker.py", line 114, in main
    price = getNight(puuid[0], puuid[1])
  File "E:\scripts\checker\NightMarket Checker\nmchecker.py", line 78, in getNight
    response = sess.get("https://pd.{region}.a.pvp.net/store/v2/storefront/{puuid}".format(
  File "C:\Users\saife\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\saife\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\saife\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\saife\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='pd.tr.a.pvp.net', port=443): Max retries exceeded with url: /store/v2/storefront/4facd75b-7814-5821-b035-8402bee2aef9 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001BB892C5640>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))
```

**Comment by UgaBugaBoo** [comment]
These are the list of Regions 

NA      - North America
EU      - Europe
BR      - Brazil
AP      - Asia Pacific
KR      - Korea
LATAM   - Latin America

**Comment by saifeealii** [comment]
> These are the list of Regions
> 
> NA - North America EU - Europe BR - Brazil AP - Asia Pacific KR - Korea LATAM - Latin America

OMG my bad.. turkey region falls under EU. i am soo noob. pls close the issue when you see it dev. Apologies.
